export interface LicenseInfo {
  tier: string;
  features: string[];
  expiresAt: Date;
}

export const TIER_FEATURES: Record<string, string[]> = {
  Basic: ['BOOKINGS', 'CLIENTS', 'EMPLOYEES', 'PAYMENTS', 'INVOICES', 'NOTIFICATIONS'],
  Pro: ['BOOKINGS', 'CLIENTS', 'EMPLOYEES', 'PAYMENTS', 'INVOICES', 'NOTIFICATIONS', 'GROUPS', 'WAITLIST', 'INTAKE_FORMS', 'RATINGS', 'REPORTS'],
  Enterprise: ['BOOKINGS', 'CLIENTS', 'EMPLOYEES', 'PAYMENTS', 'INVOICES', 'NOTIFICATIONS', 'GROUPS', 'WAITLIST', 'INTAKE_FORMS', 'RATINGS', 'REPORTS', 'AI_CHATBOT', 'ZATCA', 'CUSTOM_ROLES', 'INTEGRATIONS', 'ACTIVITY_LOG'],
};
