-- CreateExtension (disabled for local dev — pgvector not available on all dev machines)
-- CREATE EXTENSION IF NOT EXISTS "vector";

-- AlterTable "DocumentChunk" disabled for local dev (requires pgvector)
-- ALTER TABLE "DocumentChunk" ALTER COLUMN "embedding" SET DATA TYPE vector(1536);

-- CreateEnum
CREATE TYPE "RecurringPattern" AS ENUM ('DAILY', 'WEEKLY', 'BIWEEKLY', 'MONTHLY');

-- AlterTable
ALTER TABLE "Service" ADD COLUMN     "allowRecurring" BOOLEAN NOT NULL DEFAULT false,
ADD COLUMN     "allowedRecurringPatterns" "RecurringPattern"[] DEFAULT ARRAY[]::"RecurringPattern"[],
ADD COLUMN     "bufferMinutes" INTEGER NOT NULL DEFAULT 0,
ADD COLUMN     "depositAmount" DECIMAL(12,2),
ADD COLUMN     "depositEnabled" BOOLEAN NOT NULL DEFAULT false,
ADD COLUMN     "hideDurationOnBooking" BOOLEAN NOT NULL DEFAULT false,
ADD COLUMN     "hidePriceOnBooking" BOOLEAN NOT NULL DEFAULT false,
ADD COLUMN     "iconBgColor" TEXT,
ADD COLUMN     "iconName" TEXT,
ADD COLUMN     "isHidden" BOOLEAN NOT NULL DEFAULT false,
ADD COLUMN     "maxAdvanceDays" INTEGER,
ADD COLUMN     "maxParticipants" INTEGER NOT NULL DEFAULT 1,
ADD COLUMN     "maxRecurrences" INTEGER,
ADD COLUMN     "minLeadMinutes" INTEGER,
ADD COLUMN     "minParticipants" INTEGER NOT NULL DEFAULT 1,
ADD COLUMN     "reserveWithoutPayment" BOOLEAN NOT NULL DEFAULT false;

-- CreateIndex
CREATE INDEX "Service_tenantId_isHidden_idx" ON "Service"("tenantId", "isHidden");

-- CHECK constraints (not generated by Prisma — added manually)
ALTER TABLE "Service"
  ADD CONSTRAINT "chk_service_deposit"
  CHECK ("depositAmount" IS NULL OR "depositAmount" <= "price");

ALTER TABLE "Service"
  ADD CONSTRAINT "chk_service_participants"
  CHECK ("minParticipants" <= "maxParticipants");

ALTER TABLE "Service"
  ADD CONSTRAINT "chk_service_max_participants"
  CHECK ("maxParticipants" >= 1);
