# -*- coding: utf-8 -*-
"""توليد ملف E2E للسيناريوهات - موديول العملاء فقط"""
import openpyxl
from openpyxl.styles import Font, PatternFill, Alignment, Border, Side
from copy import copy

SRC = r"C:\Users\tarii\Downloads\e2e_test_template.xlsx"
OUT = r"C:\Users\tarii\Downloads\e2e_test_clients.xlsx"

wb = openpyxl.load_workbook(SRC)
ws = wb["E2E Test Cases"]

# قراءة رؤوس الأعمدة الأصلية
original_headers = [c.value for c in ws[1]]
# سنضيف عمود "Module Name" صراحة (هو موجود أصلاً، لذا سنستخدمه)
# الرؤوس: Test ID | Module | Test Type | Test Scenario | Test Case Title | Preconditions | Test Steps | Test Data | Expected Result | Actual Result | Priority | Status | Environment | Executed By | Execution Date | Notes

# حذف الصفوف الموجودة (ابقاء الرؤوس)
ws.delete_rows(2, ws.max_row)

MODULE = "Clients (العملاء)"
ENV = "Staging"
STATUS = "Not Started"

# كل سيناريو: (test_type, scenario, title, preconditions, steps, data, expected, priority)
cases = [
    # ========== CREATE (إنشاء عميل) ==========
    ("Positive","إنشاء عميل walk-in بالبيانات الأساسية",
     "إنشاء عميل جديد (walk-in) بالحد الأدنى من الحقول (الاسم الأول + الأخير + الجوال)",
     "1. تسجيل دخول مستخدم بصلاحية إنشاء عميل\n2. وجود مستأجر نشط (tenant)\n3. لا يوجد عميل بنفس الجوال داخل نفس المستأجر",
     "1. افتح /clients\n2. اضغط زر (إضافة مستفيد)\n3. أدخل الاسم الأول: أحمد\n4. أدخل الاسم الأخير: العلي\n5. أدخل الجوال: +966501234567\n6. اضغط (إضافة مستفيد)",
     "firstName=أحمد\nlastName=العلي\nphone=+966501234567",
     "1. POST /dashboard/people/clients يعيد 201\n2. Toast نجاح: تم إضافة المستفيد\n3. التوجيه إلى /clients\n4. ظهور العميل الجديد في القائمة\n5. accountType=WALK_IN افتراضياً\n6. isActive=true افتراضياً\n7. source=WALK_IN افتراضياً",
     "P1-High"),

    ("Positive","إنشاء عميل بجميع الحقول الاختيارية",
     "إنشاء عميل بحقول كاملة (الجنس، الجنسية، فصيلة الدم، جهة اتصال طوارئ، ملاحظات طبية)",
     "1. مستخدم بصلاحية إنشاء\n2. جوال فريد",
     "1. افتح /clients/create\n2. املأ جميع الحقول (اسم، جوال، بريد، جنس، تاريخ ميلاد، جنسية، هوية، جهة طوارئ، فصيلة دم، حساسية، أمراض مزمنة)\n3. اضغط حفظ",
     "الاسم+جوال صالح+email=a@b.com\ngender=male\nbloodType=O_POS\nnationalId=1012345678",
     "1. 201 Created\n2. تخزين جميع الحقول\n3. name يُركّب من firstName+middleName+lastName\n4. Toast نجاح",
     "P1-High"),

    ("Positive","إنشاء عميل - phone يعود isExisting=true",
     "إدخال جوال مستخدم مسبقاً لعميل موجود - يجب التعامل معه كربط لا إنشاء",
     "وجود عميل سابق بنفس الجوال (غير محذوف)",
     "1. افتح /clients/create\n2. أدخل جوال عميل مسجّل مسبقاً\n3. اضغط حفظ",
     "phone=+966501111111 (موجود مسبقاً)",
     "1. Toast: المستفيد مسجّل مسبقاً (info)\n2. التوجيه إلى /clients\n3. لا يتم إنشاء عميل مكرر",
     "P1-High"),

    ("Negative","إنشاء - جوال بصيغة خاطئة (بدون +966)",
     "محاولة إنشاء عميل بصيغة جوال غير سعودية",
     "مستخدم مسجّل الدخول",
     "1. افتح /clients/create\n2. أدخل الاسم\n3. أدخل الجوال: 0501234567\n4. اضغط حفظ",
     "phone=0501234567",
     "1. رسالة خطأ تحت الحقل: رقم سعودي غير صحيح — مثال +966501234567\n2. لا يتم إرسال الطلب للخادم\n3. البقاء في نفس الصفحة",
     "P1-High"),

    ("Negative","إنشاء - جوال بصيغة +966 لكن بدون 5 بعد 966",
     "regex لا يقبل إلا +9665XXXXXXXX",
     "—",
     "1. أدخل جوال: +966401234567\n2. احفظ",
     "phone=+966401234567",
     "1. خطأ Zod: رقم سعودي غير صحيح\n2. عدم إرسال الطلب",
     "P2-Medium"),

    ("Negative","إنشاء - جوال طويل/قصير",
     "أرقام ليست 13 حرفاً إجمالاً",
     "—",
     "1. أدخل +9665123456789 (زائد رقم)\n2. أو +96650123456 (ناقص)\n3. احفظ",
     "phone=+9665123456789 أو +96650123456",
     "1. خطأ regex تحت الحقل\n2. زر الحفظ لا يرسل الطلب",
     "P2-Medium"),

    ("Negative","إنشاء - جوال مكرر في نفس المستأجر (Conflict 409)",
     "backend يرمي 409 إذا كان الجوال موجوداً (الواجهة تعامله كـ isExisting)",
     "عميل نشط بجوال X",
     "1. من Postman أو عبر التجاوز: أرسل POST بنفس الجوال",
     "phone مكرر",
     "1. backend: 409 Conflict أو 200 مع isExisting=true (حسب المنطق)\n2. UI: Toast معلوماتي\n3. لا يُنشأ سجل مكرر",
     "P1-High"),

    ("Negative","إنشاء - firstName فارغ",
     "الاسم الأول مطلوب (min(1))",
     "—",
     "1. اترك firstName فارغاً\n2. املأ الباقي\n3. احفظ",
     "firstName=\"\"",
     "1. خطأ Zod تحت الحقل\n2. عدم إرسال الطلب",
     "P1-High"),

    ("Negative","إنشاء - lastName فارغ",
     "الاسم الأخير مطلوب",
     "—",
     "1. اترك lastName فارغاً\n2. احفظ",
     "lastName=\"\"",
     "1. خطأ Zod: الحقل مطلوب\n2. عدم إرسال",
     "P1-High"),

    ("Negative","إنشاء - firstName يتجاوز 255 حرف",
     "max length 255",
     "—",
     "1. أدخل 256 حرف في firstName\n2. احفظ",
     "firstName=\"a\"*256",
     "1. خطأ Zod: تجاوز الطول\n2. عدم إرسال",
     "P3-Low"),

    ("Negative","إنشاء - email بصيغة خاطئة",
     "تحقق email format",
     "—",
     "1. أدخل email=not-an-email\n2. احفظ",
     "email=not-an-email",
     "1. خطأ تحت الحقل\n2. عدم إرسال",
     "P2-Medium"),

    ("Negative","إنشاء - dateOfBirth بالمستقبل",
     "DatePicker يحد maxDate بتاريخ اليوم",
     "—",
     "1. افتح DatePicker لتاريخ الميلاد\n2. حاول اختيار تاريخ مستقبلي",
     "dateOfBirth=2030-01-01",
     "1. DatePicker يمنع الاختيار\n2. لا يتم تحديث الحقل",
     "P2-Medium"),

    ("Negative","إنشاء - gender enum غير صالح",
     "gender يجب MALE أو FEMALE",
     "—",
     "1. عبر الـ API: أرسل gender=OTHER",
     "gender=OTHER",
     "1. 400 Bad Request من backend\n2. رسالة خطأ enum",
     "P2-Medium"),

    ("Negative","إنشاء - bloodType غير موجود في الـ enum",
     "Invalid blood type",
     "—",
     "1. عبر الـ API: أرسل bloodType=XX",
     "bloodType=XX",
     "1. 400 Bad Request\n2. Validation error",
     "P3-Low"),

    ("Negative","إنشاء - nationalId يتجاوز 20 حرف",
     "max 20",
     "—",
     "1. أدخل nationalId=\"1\"*21\n2. احفظ",
     "nationalId طول 21",
     "1. خطأ Zod\n2. عدم إرسال",
     "P3-Low"),

    ("Negative","إنشاء - allergies > 1000 حرف",
     "max 1000",
     "—",
     "1. أدخل حساسية بـ 1001 حرف\n2. احفظ",
     "allergies طوله 1001",
     "1. خطأ تحت الحقل\n2. عدم إرسال",
     "P3-Low"),

    ("Negative","إنشاء - notes > 2000 حرف (backend)",
     "max 2000",
     "—",
     "1. API: notes طول 2001",
     "notes طوله 2001",
     "1. 400 Bad Request",
     "P3-Low"),

    ("Negative","إنشاء - emergencyPhone بصيغة خاطئة",
     "نفس regex للجوال",
     "—",
     "1. أدخل emergencyPhone=0501234567\n2. احفظ",
     "emergencyPhone=0501234567",
     "1. خطأ تحت الحقل\n2. عدم إرسال",
     "P2-Medium"),

    ("Negative","إنشاء - بدون تسجيل دخول (401)",
     "يجب JWT صالح",
     "الخروج من الحساب",
     "1. API مباشر: POST /dashboard/people/clients دون Bearer",
     "no Authorization header",
     "1. 401 Unauthorized\n2. UI: إعادة توجيه إلى تسجيل الدخول",
     "P1-High"),

    ("Negative","إنشاء - مستخدم بدون صلاحية (403)",
     "CASL guard يمنع",
     "مستخدم بدور بدون صلاحية create client",
     "1. تسجيل دخول بمستخدم محدود\n2. محاولة إنشاء عميل",
     "—",
     "1. 403 Forbidden\n2. Toast خطأ",
     "P1-High"),

    # ========== UPDATE ==========
    ("Positive","تعديل حقل واحد فقط (firstName)",
     "تحديث جزئي (PATCH)",
     "عميل موجود",
     "1. افتح /clients/[id]/edit\n2. غيّر firstName فقط\n3. احفظ",
     "firstName=محمد",
     "1. 200 OK\n2. Toast: تم حفظ التعديلات\n3. التوجيه لـ /clients\n4. إعادة تركيب name",
     "P1-High"),

    ("Positive","تعديل جميع الحقول + تفعيل الحساب",
     "Switch isActive يعمل",
     "عميل غير نشط",
     "1. افتح edit\n2. فعّل Switch (isActive)\n3. احفظ",
     "isActive=true",
     "1. 200\n2. status badge يتغير للنشط في القائمة",
     "P1-High"),

    ("Positive","تعديل الجوال إلى قيمة فريدة",
     "يسمح بتغيير الجوال إلى قيمة غير مستخدمة",
     "عميل موجود + جوال جديد غير مكرر",
     "1. افتح edit\n2. غيّر الجوال\n3. احفظ",
     "phone=+966509999999",
     "1. 200 OK\n2. فحص التكرار يمر\n3. الجوال القديم محرّر",
     "P1-High"),

    ("Positive","تعديل - إبقاء نفس الجوال (skip duplicate check)",
     "handler يتخطى فحص التكرار إذا لم يتغير الجوال",
     "—",
     "1. edit\n2. لا تغيّر الجوال\n3. احفظ",
     "phone=نفس القديم",
     "1. 200 OK\n2. لا Conflict",
     "P2-Medium"),

    ("Positive","تعديل - مسح حقل اختياري (set null)",
     "يمكن صراحة null لمسح القيمة",
     "عميل فيه notes سابقة",
     "1. edit\n2. امسح حقل notes\n3. احفظ",
     "notes=\"\" -> null",
     "1. 200\n2. notes=null في DB",
     "P2-Medium"),

    ("Negative","تعديل عميل غير موجود (404)",
     "id خاطئ",
     "—",
     "1. افتح /clients/INVALID-ID/edit",
     "id=uuid عشوائي",
     "1. 404 Not Found\n2. UI: رسالة + زر العودة",
     "P1-High"),

    ("Negative","تعديل عميل محذوف ناعمياً (404)",
     "handler يفلتر deletedAt=null",
     "عميل deletedAt != null",
     "1. API: PATCH /clients/:deletedId",
     "—",
     "1. 404 Not Found",
     "P1-High"),

    ("Negative","تعديل الجوال إلى قيمة مكررة (409)",
     "فحص التكرار",
     "عميلان، الأول له phoneA والثاني phoneB",
     "1. edit للثاني\n2. غيّر الجوال إلى phoneA\n3. احفظ",
     "phone=phoneA",
     "1. 409 Conflict\n2. Toast: الجوال مكرر",
     "P1-High"),

    ("Negative","تعديل - phone regex خاطئ",
     "—",
     "—",
     "1. edit\n2. أدخل phone=0501234567\n3. احفظ",
     "phone=0501234567",
     "1. خطأ Zod تحت الحقل",
     "P1-High"),

    ("Negative","تعديل - طول حقل تجاوز الحد",
     "firstName>255 مثلاً",
     "—",
     "1. edit\n2. أدخل firstName طويل\n3. احفظ",
     "firstName>255",
     "1. خطأ Zod\n2. عدم إرسال",
     "P3-Low"),

    ("Negative","تعديل - بدون صلاحية (403)",
     "CASL يمنع",
     "مستخدم محدود",
     "1. محاولة PATCH",
     "—",
     "1. 403\n2. Toast: فشل تحديث البيانات",
     "P1-High"),

    # ========== DELETE ==========
    ("Positive","حذف عميل (soft delete)",
     "تأكيد الحذف من الـ dialog",
     "عميل موجود",
     "1. /clients\n2. اضغط أيقونة الحذف للعميل\n3. في الـ Dialog اضغط (حذف)",
     "id=XXX",
     "1. 204 No Content\n2. Toast: تم حذف المستفيد\n3. إغلاق الـ dialog\n4. إعادة تحميل القائمة\n5. العميل غير ظاهر\n6. DB: deletedAt, isActive=false, phone=null, notes يحتوي [deleted-phone:...]",
     "P1-High"),

    ("Positive","حذف - إعادة استخدام الجوال بعد الحذف",
     "الجوال يصبح متاحاً للاستخدام",
     "عميل A محذوف بجوال X",
     "1. أنشئ عميلاً B بنفس الجوال X",
     "phone=X",
     "1. 201 Created ينجح\n2. لا تعارض لأن القديم phone=null",
     "P2-Medium"),

    ("Negative","حذف عميل غير موجود (404)",
     "id غير موجود",
     "—",
     "1. DELETE /clients/INVALID",
     "—",
     "1. 404 Not Found",
     "P2-Medium"),

    ("Negative","حذف عميل محذوف مسبقاً (404)",
     "deletedAt != null -> 404",
     "—",
     "1. DELETE نفس id مرتين",
     "—",
     "1. الثانية ترجع 404",
     "P2-Medium"),

    ("Negative","حذف - إلغاء من الـ Dialog",
     "إغلاق بدون إجراء",
     "—",
     "1. افتح dialog الحذف\n2. اضغط (إلغاء)",
     "—",
     "1. إغلاق الـ Dialog\n2. لا طلب DELETE\n3. العميل باقٍ",
     "P2-Medium"),

    ("Negative","حذف - Escape key يغلق الـ Dialog",
     "UX",
     "—",
     "1. افتح dialog\n2. اضغط Esc",
     "—",
     "1. إغلاق دون حذف",
     "P3-Low"),

    ("Negative","حذف - بدون صلاحية (403)",
     "CASL",
     "مستخدم محدود",
     "1. محاولة DELETE",
     "—",
     "1. 403\n2. Toast: فشل حذف المستفيد",
     "P1-High"),

    # ========== GET BY ID ==========
    ("Positive","عرض تفاصيل عميل",
     "صفحة /clients/[id]",
     "—",
     "1. /clients/[id]",
     "—",
     "1. 200\n2. عرض الاسم + الصورة (initials)\n3. 4 Tabs (التواصل، المواعيد، الفواتير، الإحصائيات)\n4. بطاقات: شخصي، تواصل، طبي، حساب",
     "P1-High"),

    ("Positive","عرض - شارة Walk-in",
     "accountType=WALK_IN تظهر شارة",
     "عميل walk-in",
     "1. /clients/[walkin-id]",
     "—",
     "1. شارة برتقالية Walk-in ظاهرة",
     "P2-Medium"),

    ("Positive","عرض - شارة نشط/غير نشط",
     "—",
     "—",
     "1. افتح عميل نشط وآخر غير نشط",
     "—",
     "1. شارة خضراء (نشط) / رمادية (غير نشط)",
     "P2-Medium"),

    ("Negative","عرض عميل غير موجود (404)",
     "—",
     "—",
     "1. /clients/INVALID",
     "—",
     "1. Error banner: لم يتم العثور على المستفيد\n2. زر: العودة للمستفيدين",
     "P1-High"),

    ("Negative","عرض عميل محذوف (404)",
     "deletedAt=null filter",
     "—",
     "1. /clients/[deleted]",
     "—",
     "1. 404 + Error banner",
     "P2-Medium"),

    # ========== LIST / SEARCH / FILTER ==========
    ("Positive","قائمة العملاء - Pagination",
     "20 عنصر لكل صفحة",
     "> 20 عميل",
     "1. /clients\n2. تنقل بين الصفحات",
     "—",
     "1. 20 صف في الصفحة الأولى\n2. meta.totalPages صحيح\n3. keepPreviousData أثناء التحميل",
     "P1-High"),

    ("Positive","بحث بالاسم",
     "يبحث في name, firstName, lastName, phone, email",
     "—",
     "1. /clients\n2. اكتب جزء من الاسم في البحث",
     "search=أحمد",
     "1. debounced\n2. يعيد الصفحة إلى 1\n3. نتائج مطابقة (OR لخمسة حقول)",
     "P1-High"),

    ("Positive","بحث بالجوال",
     "—",
     "—",
     "1. اكتب الجوال أو جزء منه",
     "search=966501",
     "1. يظهر من جواله يطابق",
     "P2-Medium"),

    ("Positive","بحث - case insensitive",
     "contains insensitive",
     "—",
     "1. ابحث بحروف كبيرة/صغيرة",
     "search=AHMED vs ahmed",
     "1. نفس النتائج",
     "P2-Medium"),

    ("Positive","بحث - نص عربي",
     "localeCompare ar",
     "—",
     "1. ابحث بكلمة عربية",
     "search=سالم",
     "1. نتائج صحيحة",
     "P2-Medium"),

    ("Positive","فلتر - isActive=true",
     "—",
     "—",
     "1. اختر فلتر (نشط)",
     "isActive=true",
     "1. النتائج نشطة فقط\n2. page=1",
     "P2-Medium"),

    ("Positive","فلتر - isActive=false",
     "تحويل string 'false' إلى boolean صحيح",
     "—",
     "1. اختر فلتر (غير نشط)",
     "isActive=false",
     "1. غير النشطين فقط\n2. لا خطأ تحويل النوع",
     "P2-Medium"),

    ("Positive","فلتر - gender (API)",
     "—",
     "—",
     "1. GET /clients?gender=MALE",
     "gender=MALE",
     "1. ذكور فقط",
     "P3-Low"),

    ("Positive","فلتر - source (API)",
     "WALK_IN/ONLINE/REFERRAL",
     "—",
     "1. GET /clients?source=WALK_IN",
     "source=WALK_IN",
     "1. walk-in فقط",
     "P3-Low"),

    ("Positive","إعادة تعيين الفلاتر (Reset)",
     "زر يظهر عند وجود فلتر نشط",
     "فلتر مفعّل",
     "1. اضغط (إعادة تعيين)",
     "—",
     "1. مسح البحث والفلاتر\n2. page=1",
     "P2-Medium"),

    ("Positive","Toggle نشط/غير نشط من القائمة",
     "زر أيقوني بالصف",
     "—",
     "1. اضغط أيقونة الحظر/التفعيل",
     "—",
     "1. mutation تُنفّذ\n2. Toast نجاح: تم تفعيل/تعطيل الحساب\n3. تحديث الشارة",
     "P1-High"),

    ("Negative","Toggle - فشل الشبكة",
     "—",
     "قطع الاتصال",
     "1. اضغط toggle\n2. دع الطلب يفشل",
     "—",
     "1. Toast: فشل تفعيل/تعطيل الحساب\n2. حالة الزر ترجع",
     "P2-Medium"),

    ("Negative","قائمة - limit > 200",
     "حد أقصى 200",
     "—",
     "1. GET /clients?limit=500",
     "limit=500",
     "1. 400 Bad Request",
     "P2-Medium"),

    ("Negative","قائمة - page < 1",
     "min 1",
     "—",
     "1. GET /clients?page=0",
     "page=0",
     "1. 400 Bad Request",
     "P2-Medium"),

    ("Negative","قائمة - بحث بدون نتائج",
     "—",
     "—",
     "1. ابحث بنص غير موجود",
     "search=XXNOTEXISTXX",
     "1. حالة فارغة: لا يوجد مستفيدون\n2. زر: إضافة مستفيد",
     "P2-Medium"),

    ("Negative","قائمة - tenant isolation",
     "tenantId scoped",
     "مستخدم في tenant A + عميل في tenant B",
     "1. محاولة الوصول لعميل من tenant آخر",
     "—",
     "1. لا يظهر في القائمة\n2. GET by id -> 404",
     "P1-High"),

    # ========== MOBILE PROFILE ==========
    ("Positive","Mobile - عرض ملف العميل نفسه",
     "GET /mobile/client/profile",
     "عميل مسجل دخول في التطبيق",
     "1. افتح التطبيق\n2. اذهب للبروفايل",
     "JWT client",
     "1. 200\n2. عرض بيانات الحساب\n3. clientId من JWT تلقائياً",
     "P1-High"),

    ("Positive","Mobile - تحديث البروفايل",
     "PATCH /mobile/client/profile",
     "—",
     "1. الإعدادات\n2. عدّل اسم أو جوال\n3. احفظ",
     "name=أحمد محمد",
     "1. 200\n2. name يُفكّك إلى firstName/lastName\n3. قواعد phone/email نفسها",
     "P1-High"),

    ("Negative","Mobile - بدون JWT (401)",
     "—",
     "logout",
     "1. محاولة GET /mobile/client/profile",
     "—",
     "1. 401 Unauthorized\n2. إعادة التوجيه لتسجيل الدخول",
     "P1-High"),

    ("Negative","Mobile - العميل محذوف (404)",
     "deletedAt filter",
     "—",
     "1. GET /mobile/client/profile",
     "—",
     "1. 404",
     "P2-Medium"),

    ("Negative","Mobile - محاولة تعديل clientId غير clientId الـ JWT",
     "الـ controller يجبر clientId من user.sub",
     "—",
     "1. PATCH مع body.clientId مختلف",
     "body.clientId=other",
     "1. يُتجاهل ويُستبدل بـ user.sub\n2. لا وصول لسجلات غيره",
     "P1-High"),

    ("Positive","Mobile - تسجيل خروج العميل",
     "Logout flow",
     "—",
     "1. البروفايل\n2. اضغط تسجيل الخروج\n3. تأكيد",
     "—",
     "1. حوار تأكيد\n2. مسح التوكن\n3. redirect /auth/login",
     "P2-Medium"),

    # ========== RTL / UI / Network ==========
    ("Positive","RTL - phone/email بـ dir=ltr",
     "تنسيق الأرقام والبريد بـ LTR داخل صفحة RTL",
     "—",
     "1. افتح تفاصيل عميل",
     "—",
     "1. رقم الجوال LTR\n2. البريد LTR\n3. الهوية LTR",
     "P2-Medium"),

    ("Positive","RTL - ترتيب الـ Tabs RTL",
     "dir=rtl on tabs",
     "—",
     "1. افتح detail",
     "—",
     "1. الترتيب معكوس صحيح",
     "P3-Low"),

    ("Positive","Double-click submit - طلب واحد",
     "mutation.isPending يمنع المكرر",
     "—",
     "1. اضغط زر الحفظ مرتين بسرعة",
     "—",
     "1. طلب واحد فقط يُرسل",
     "P2-Medium"),

    ("Positive","Debounced search",
     "—",
     "—",
     "1. اكتب 5 حروف بسرعة",
     "—",
     "1. طلب واحد بآخر قيمة",
     "P2-Medium"),

    ("Negative","خطأ شبكة - إنشاء",
     "—",
     "قطع الاتصال",
     "1. احفظ نموذج إنشاء",
     "—",
     "1. Toast خطأ\n2. البقاء بالنموذج\n3. لا فقدان بيانات",
     "P1-High"),

    ("Negative","خطأ شبكة - قائمة",
     "—",
     "قطع الاتصال",
     "1. افتح /clients",
     "—",
     "1. Error Banner\n2. لا كراش",
     "P2-Medium"),

    ("Negative","خطأ 500 من الخادم",
     "—",
     "خادم يُعيد 500",
     "1. عند أي عملية",
     "—",
     "1. Toast/Banner: رسالة عامة\n2. لا تعطّل التطبيق",
     "P2-Medium"),

    ("Negative","Stale data بعد 5 دقائق",
     "staleTime=5m list, 10m detail",
     "—",
     "1. افتح /clients\n2. انتظر 5 دقائق\n3. ارجع للصفحة",
     "—",
     "1. إعادة الجلب تلقائياً",
     "P3-Low"),

    ("Positive","Skeleton أثناء التحميل الأول",
     "5 صفوف h-12",
     "—",
     "1. افتح /clients أول مرة",
     "—",
     "1. skeletons 5\n2. StatsGrid skeletons إذا وجدت",
     "P3-Low"),

    ("Negative","عرض الأحرف الأولى بأسماء عربية",
     "Avatar initials مع Unicode",
     "—",
     "1. افتح عميل باسم عربي",
     "firstName=أحمد, lastName=السعيد",
     "1. الأحرف تظهر صحيحة (أ + ا)",
     "P3-Low"),

    ("Positive","فرز - localeCompare عربي",
     "—",
     "—",
     "1. اضغط فرز على الاسم",
     "—",
     "1. ترتيب عربي صحيح",
     "P3-Low"),

    # ========== Ratings / History (Related) ==========
    ("Positive","Employee يعرض سجل العميل",
     "GET /mobile/employee/clients/:id/history",
     "employee مسجّل + حجوزات مع clientId",
     "1. API call",
     "clientId=X",
     "1. آخر 20 حجز\n2. كل الحالات\n3. scheduledAt DESC",
     "P2-Medium"),

    ("Positive","Employee يعرض قائمة عملائه",
     "GET /mobile/employee/clients",
     "—",
     "1. API call",
     "—",
     "1. عملاء distinct من حجوزاته\n2. ترتيب الاسم ASC\n3. pagination",
     "P2-Medium"),

    ("Positive","تقييم عميل لموظف (rating)",
     "one per booking",
     "booking مكتمل بدون تقييم",
     "1. POST /ratings\n2. score=5, comment",
     "bookingId, score=5",
     "1. 201\n2. rating مخزّن",
     "P2-Medium"),

    ("Negative","تقييم - score خارج النطاق (0 أو 6)",
     "1-5",
     "—",
     "1. score=0 ثم 6",
     "—",
     "1. 400 Bad Request",
     "P2-Medium"),

    ("Negative","تقييم - مكرر لنفس الحجز",
     "bookingId unique",
     "تقييم موجود",
     "1. POST ثانٍ بنفس bookingId",
     "—",
     "1. 409 Conflict",
     "P2-Medium"),

    # ========== Concurrency / Security ==========
    ("Negative","Concurrency - إنشاء بنفس الجوال متزامناً",
     "two requests same phone",
     "—",
     "1. أرسل POST بنفس الجوال من 2 clients",
     "—",
     "1. واحد ينجح + الآخر 409\n2. لا ازدواجية DB (unique constraint)",
     "P2-Medium"),

    ("Negative","SQL/NoSQL injection في search",
     "Prisma يستخدم prepared statements",
     "—",
     "1. search=' OR 1=1 --",
     "—",
     "1. لا تنفيذ SQL\n2. بحث آمن",
     "P1-High"),

    ("Negative","XSS في الاسم أو notes",
     "React يُهرب تلقائياً",
     "—",
     "1. أنشئ عميل باسم <script>alert(1)</script>",
     "—",
     "1. النص يُعرض حرفياً\n2. لا تنفيذ",
     "P1-High"),

    ("Negative","CSRF - طلب من دومين آخر",
     "JWT Bearer فقط",
     "—",
     "1. طلب من origin آخر",
     "—",
     "1. CORS يرفض أو لا JWT → 401",
     "P1-High"),
]

# كتابة الصفوف
for idx, (ttype, scenario, title, pre, steps, data, expected, prio) in enumerate(cases, start=1):
    tid = f"CL-{idx:03d}"
    ws.append([tid, MODULE, ttype, scenario, title, pre, steps, data, expected, None, prio, STATUS, ENV, None, None, None])

# تنسيق: wrap text لأعمدة النصوص الطويلة
wrap_cols = [4,5,6,7,8,9,16]
for col in wrap_cols:
    for row in ws.iter_rows(min_row=2, min_col=col, max_col=col):
        for cell in row:
            cell.alignment = Alignment(wrap_text=True, vertical="top")

# عرض الأعمدة
widths = {1:10, 2:20, 3:10, 4:32, 5:40, 6:28, 7:40, 8:28, 9:40, 10:18, 11:10, 12:12, 13:12, 14:14, 15:14, 16:20}
for c, w in widths.items():
    ws.column_dimensions[openpyxl.utils.get_column_letter(c)].width = w

# تجميد الصف العلوي
ws.freeze_panes = "A2"

# تحديث ورقة الملخص - الصيغ ستعمل تلقائياً مع البيانات الجديدة
wb.save(OUT)
print(f"Saved: {OUT}")
print(f"Total test cases: {len(cases)}")
