export { initClient, apiRequest, ApiError } from './client.js'
export type { ClientConfig } from './client.js'
export * from './types/index.js'
export * as authApi from './modules/auth.js'
export * as featureFlagsApi from './modules/feature-flags.js'
export * as whitelabelApi from './modules/whitelabel.js'
export * as bookingsApi from './modules/bookings.js'
export * as clientsApi from './modules/clients.js'
export * as employeesApi from './modules/employees.js'
export * as servicesApi from './modules/services.js'
export * as branchesApi from './modules/branches.js'
export * as departmentsApi from './modules/departments.js'
export * as specialtiesApi from './modules/specialties.js'
export * as availabilityApi from './modules/availability.js'
export * as ratingsApi from './modules/ratings.js'
export * as paymentsApi from './modules/payments.js'
export * as invoicesApi from './modules/invoices.js'
export * as couponsApi from './modules/coupons.js'
export * as themeApi from './modules/theme.js'
export * as intakeFormsApi from './modules/intake-forms.js'
export * as notificationsApi from './modules/notifications.js'
export * as reportsApi from './modules/reports.js'
export * as chatbotAdminApi from './modules/chatbot-admin.js'
export * as groupsApi from './modules/groups.js'
export * as usersApi from './modules/users.js'
export * as organizationSettingsApi from "./modules/organization-settings.js"
export type { OrganizationSettings, UpdateOrganizationSettingsPayload } from "./modules/organization-settings.js"
