export { initClient, apiRequest, ApiError } from './client.js'
export type { ClientConfig } from './client.js'
export * from './types/index.js'
export * as authApi from './modules/auth.js'
export * as featureFlagsApi from './modules/feature-flags.js'
export * as whitelabelApi from './modules/whitelabel.js'
export * as bookingsApi from './modules/bookings.js'
export * as patientsApi from './modules/patients.js'
export * as practitionersApi from './modules/practitioners.js'
