export { initClient, apiRequest, ApiError } from './client.js'
export type { ClientConfig } from './client.js'
export * from './types/index.js'
export * as authApi from './modules/auth.js'
export * as featureFlagsApi from './modules/feature-flags.js'
export * as whitelabelApi from './modules/whitelabel.js'
export * as bookingsApi from './modules/bookings.js'
export * as patientsApi from './modules/patients.js'
export * as practitionersApi from './modules/practitioners.js'
export * as servicesApi from './modules/services.js'
export * as branchesApi from './modules/branches.js'
export * as departmentsApi from './modules/departments.js'
export * as specialtiesApi from './modules/specialties.js'
export * as availabilityApi from './modules/availability.js'
export * as ratingsApi from './modules/ratings.js'
export * as paymentsApi from './modules/payments.js'
export * as invoicesApi from './modules/invoices.js'
export * as couponsApi from './modules/coupons.js'
export * as giftCardsApi from './modules/gift-cards.js'
