import { HugeiconsIcon, type IconSvgElement } from '@hugeicons/react'
import {
  Add01Icon, Alert02Icon, ArrowLeft01Icon, ArrowRight01Icon,
  BotIcon, Building03Icon, Building04Icon,
  Calendar03Icon, CalendarAdd02Icon, CalendarRemove02Icon,
  Cancel01Icon, CancelCircleIcon,
  ChartBarBigIcon, ChartLineData01Icon, CheckmarkCircle02Icon,
  ClinicIcon, Clock01Icon, Clock02Icon, Coins01Icon, CreditCardIcon,
  DashboardSquare01Icon, Delete02Icon,
  DiscountTag01Icon, DiscountTag02Icon,
  Doctor01Icon, Doctor02Icon, Download02Icon,
  Edit02Icon, EyeIcon, File01Icon, Folder02Icon,
  GiftIcon, HierarchyCircle01Icon, HourglassIcon,
  ImageNotFound01Icon,
  Invoice01Icon, Invoice02Icon, Invoice03Icon,
  Layers01Icon, Location01Icon, Logout01Icon,
  Mail01Icon, MedicalMaskIcon,
  MoneyBag01Icon, MoneyBag02Icon,
  Notification01Icon, Notification02Icon,
  PaintBrush02Icon, Plug01Icon, RefreshIcon,
  Search01Icon, SearchRemoveIcon,
  Settings01Icon, Settings02Icon, Shield01Icon,
  StarIcon, StethoscopeIcon, Stethoscope02Icon,
  Tag01Icon, TaxesIcon,
  Tick02Icon, TickDouble01Icon,
  UserIcon, UserAdd01Icon, UserCheck01Icon,
  UserGroupIcon, UserMultiple02Icon, UserRemove01Icon, UserSettings01Icon,
  WalkingIcon, Home01Icon,
} from '@hugeicons/core-free-icons'

const ICON_MAP: Record<string, IconSvgElement> = {
  'hgi-add-01': Add01Icon,
  'hgi-alert-02': Alert02Icon,
  'hgi-arrow-left-01': ArrowLeft01Icon,
  'hgi-arrow-right-01': ArrowRight01Icon,
  'hgi-bot': BotIcon,
  'hgi-building-03': Building03Icon,
  'hgi-building-04': Building04Icon,
  'hgi-calendar-03': Calendar03Icon,
  'hgi-calendar-add-02': CalendarAdd02Icon,
  'hgi-calendar-remove-02': CalendarRemove02Icon,
  'hgi-cancel-01': Cancel01Icon,
  'hgi-cancel-circle': CancelCircleIcon,
  'hgi-chart-bar-01': ChartBarBigIcon,
  'hgi-chart-line-data-01': ChartLineData01Icon,
  'hgi-checkmark-circle-02': CheckmarkCircle02Icon,
  'hgi-clinic': ClinicIcon,
  'hgi-clock-01': Clock01Icon,
  'hgi-clock-02': Clock02Icon,
  'hgi-coins-01': Coins01Icon,
  'hgi-credit-card': CreditCardIcon,
  'hgi-dashboard-square-01': DashboardSquare01Icon,
  'hgi-delete-02': Delete02Icon,
  'hgi-discount-tag-01': DiscountTag01Icon,
  'hgi-discount-tag-02': DiscountTag02Icon,
  'hgi-doctor-01': Doctor01Icon,
  'hgi-doctor-02': Doctor02Icon,
  'hgi-download-02': Download02Icon,
  'hgi-edit-02': Edit02Icon,
  'hgi-eye': EyeIcon,
  'hgi-file-01': File01Icon,
  'hgi-folder-02': Folder02Icon,
  'hgi-gift': GiftIcon,
  'hgi-gift-01': GiftIcon,
  'hgi-hierarchy-01': HierarchyCircle01Icon,
  'hgi-hourglass': HourglassIcon,
  'hgi-home-01': Home01Icon,
  'hgi-image-not-found-01': ImageNotFound01Icon,
  'hgi-invoice-01': Invoice01Icon,
  'hgi-invoice-02': Invoice02Icon,
  'hgi-invoice-03': Invoice03Icon,
  'hgi-layers-01': Layers01Icon,
  'hgi-location-01': Location01Icon,
  'hgi-logout-01': Logout01Icon,
  'hgi-mail-01': Mail01Icon,
  'hgi-medical-mask': MedicalMaskIcon,
  'hgi-money-bag-01': MoneyBag01Icon,
  'hgi-money-bag-02': MoneyBag02Icon,
  'hgi-notification-01': Notification01Icon,
  'hgi-notification-02': Notification02Icon,
  'hgi-paint-brush-02': PaintBrush02Icon,
  'hgi-plug-01': Plug01Icon,
  'hgi-refresh': RefreshIcon,
  'hgi-search-01': Search01Icon,
  'hgi-search-remove-01': SearchRemoveIcon,
  'hgi-settings-01': Settings01Icon,
  'hgi-settings-02': Settings02Icon,
  'hgi-shield-01': Shield01Icon,
  'hgi-star': StarIcon,
  'hgi-star-solid': StarIcon,
  'hgi-stethoscope': StethoscopeIcon,
  'hgi-stethoscope-02': Stethoscope02Icon,
  'hgi-tag-01': Tag01Icon,
  'hgi-tax-01': TaxesIcon,
  'hgi-tick-02': Tick02Icon,
  'hgi-tick-double-01': TickDouble01Icon,
  'hgi-user': UserIcon,
  'hgi-user-add-01': UserAdd01Icon,
  'hgi-user-check-01': UserCheck01Icon,
  'hgi-user-group': UserGroupIcon,
  'hgi-user-multiple-02': UserMultiple02Icon,
  'hgi-user-remove-01': UserRemove01Icon,
  'hgi-user-settings-01': UserSettings01Icon,
  'hgi-walking': WalkingIcon,
}

interface HIconProps {
  name: string
  size?: number
  className?: string
  color?: string
}

export function HIcon({ name, size = 20, className, color = 'currentColor' }: HIconProps) {
  // Strip hgi-stroke prefix if passed alongside icon name
  const key = name.trim().split(/\s+/).find(c => c.startsWith('hgi-') && c !== 'hgi-stroke') ?? name
  const icon = ICON_MAP[key]
  if (!icon) return null
  return <HugeiconsIcon icon={icon} size={size} color={color} className={className} strokeWidth={1.5} />
}
